(fixes issue #112) Add docs for strings review and sign-offs
mozilla-l10n/documentation pull request #117
Opened 2017-11-03 08:53 UTC by flodolo

I think this should be good for review.

2017-11-03 10:57 UTC, Pike requested changes
Can we fork this into two PRs?

I'd like to iterate over the string review part a bit more, but the sign-offs looks great already. There's just one nit about the magic of the magic of the diff UI, not sure if fixing that will improve the doc ;-)

2017-11-03 10:57 UTC, Pike commented on products/review/signoffs.md
> +By clicking the top gray circle on the rightmost column, you can display a diff between the latest changeset and the most recent sign-off. Note that both circles can be dragged, to display the diff b
Actually, all of the column can be clicked to open the diff view. Yeah, magic.

2017-11-03 11:37 UTC, flodolo commented
> Can we fork this into two PRs?

Sure. Let me keep this one for sign-offs, and split review in a different PR.

2017-11-03 11:47 UTC, flodolo commented
Moved review.md in #118

2017-11-06 17:07 UTC, Delphine approved these changes
This looks good thanks. If ever I think of more things to add I edit this doc.

2017-11-08 19:17 UTC, Pike approved these changes
I think this is good.

There's a bit that I'm wondering about: the actual review process is just the last few bits on this page. So people trying to understand what we're doing here and why probably have their head off by the time they get there.

Maybe it makes sense to reorder this doc so that the actual review comes pretty early, and then the path towards the review page is explained?

If so, good for a follow-up.

2017-11-08 19:24 UTC, flodolo commented
> Maybe it makes sense to reorder this doc so that the actual review comes pretty early, and then the path towards the review page is explained?

This is mostly for internal use (and curious folks). I'm afraid that putting that information without explaining first how diff view works, how to reach it, etc. might become really hard. Not sure if a reminder at the beginning would be enough.

I'm going to merge this, happy to iterate over the doc in the future. We'll likely come up with more checks too.

2017-11-08 19:24 UTC, merged