Add document: l10n best practices for developers
mozilla-l10n/documentation pull request #238
Opened 2021-08-26 06:03 UTC by flodolo

Fixes #224 

@mozilla-l10n/pm-group 
You might have seen this document in the past (it [used to live on MDN](https://web.archive.org/web/20210619113459/https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices) before "the purge"). 

I've taken that document, reorganized it and removed a bunch of things (localizers had access and added a lot of examples, making it very chaotic). I've also added a few things about Fluent.

Do you have time to take a look? The markdown version is available here
https://github.com/mozilla-l10n/documentation/blob/best_practices/src/localization/dev_best_practices.md

There are two things I'm interested in:
* That the English is not broken. I've been staring at this the whole week, and errors might have slipped through the cracks.
* Are there problems that you see often in your project, and are not covered here?

On the latter, I would really like to try and avoid going into too much detail for a specific format (e.g. Fluent), because we already have several documents scattered here and there, and this document is already very long. If necessary, we should think about creating a Fluent doc here, and try to gather all the information in one place.

2021-08-26 07:42 UTC, eemeli approved these changes
This looks really good. I don't recall having come across this when I went through all the docs that I could find a few weeks ago, and I wish we could get more visibility to this.

The examples of not-like-English seem to end up using Gaelic rather often. It might be good if a few of them could be switched for some other languages, to underline the point that these concerns aren't limited to any one locale?

2021-08-26 07:42 UTC, eemeli commented on src/localization/dev_best_practices.md
> +This document provides best practices for developers to create localizable code, and describes how to avoid some localizability (l12y) common mistakes. Some additional guidelines specific for Fluent
```suggestion
This document provides best practices for developers to create localizable code, and describes how to avoid some localizability common mistakes. Some additional guidelines specific for Fluent in Firefox are also available in [this page](https://firefox-source-docs.mozilla.org/l10n/fluent/review.html).
```

"l12y" isn't actually used in the rest of the document, and it's a really rather rare term. Could it be just left out?

2021-08-26 07:42 UTC, eemeli commented on src/localization/dev_best_practices.md
> +# Message comment
```suggestion
# Standalone comment

# Message comment
```

While it is explained in the linked documentation, it might be good to also include the standalone comment here as a way of pointing out that the message comment needs to not have any empty lines separating it from its associated message.

2021-08-26 07:49 UTC, flodolo commented
Thanks for taking a look!

You're correct for Gaelic, the reason we have so many examples from that language is that they were added by the localizer, and it has a lot of edge cases (capitalization, yes/no).

2021-08-26 08:20 UTC, flodolo commented on src/localization/dev_best_practices.md
> +And then replace `%S` at run-time with the second string. Note also the localization comment and make sure it is clear to the localizer which placeholder string will appear in place of the placeholde
@mathjazz 
Is this actual Slovenian, or did I make it up?

2021-08-26 08:27 UTC, mathjazz commented on src/localization/dev_best_practices.md
> +And then replace `%S` at run-time with the second string. Note also the localization comment and make sure it is clear to the localizer which placeholder string will appear in place of the placeholde
Very well done, neighbour!

2021-08-26 23:42 UTC, peiying2 reviewed
Looks good. Just some minor suggested changes. Some of the sentences in the best practice guide seems to run long and colloquial. I didn't comment on all except a few to break a long sentence into a few shorter ones.

2021-08-26 23:42 UTC, peiying2 commented on src/localization/dev_best_practices.md
> +You need to account for different grammar structures in different locales, and add switching mechanisms to present them appropriately. You shouldn’t make assumptions as to what those structures will
Punctuation: `... structures will be: instead, let locales...` I think these should be two separate sentences.

2021-08-26 23:42 UTC, peiying2 commented on src/localization/dev_best_practices.md
> +This document provides best practices for developers to create localizable code, and describes how to avoid some localizability common mistakes. Some additional guidelines specific for Fluent in Fire
Should it be `some common localizability mistakes`?

2021-08-26 23:42 UTC, peiying2 commented on src/localization/dev_best_practices.md
> +* [#l10n-community](https://chat.mozilla.org/#/room/#l10n-community:mozilla.org) is used by localizers, and it's a good place to ask for questions about specific languages.
Use curly quote.

2021-08-26 23:42 UTC, peiying2 commented on src/localization/dev_best_practices.md
> +Unfortunately, this won’t work at all: you need at least a third string to place after the link, without that some languages won’t be able to create a natural sounding sentence.
Punctuation - need to break up into three sentences.
1). ... all.
2). You need at ... after the link.
3). Without  that, some languages ...

2021-08-26 23:42 UTC, peiying2 commented on src/localization/dev_best_practices.md
> +Some CSS text/font properties may cause problems with text legibility when applied to certain scripts. For example, avoid using Italic for CJKT locales — Chinese (Simplified and Traditional), Japanes
Taiwanese refers to spoken language.

2021-08-27 01:38 UTC, Delphine requested changes
This looks really good!
Just a few comments. I'll need to think a bit more next week on if anything could be missing from here, though
thanks flod!

2021-08-27 01:38 UTC, Delphine commented on src/localization/dev_best_practices.md
> +* The string contains an adjective, but the noun it refers to it’s not part of the string. Most languages need to decline adjectives based on number and gender.
Nit: (...) but the noun it refers to *is* not part of the string

2021-08-27 01:38 UTC, Delphine commented on src/localization/dev_best_practices.md
> +In case of Fluent and Firefox, it’s possible to save these strings in a file that it’s not exposed to localization ([example](https://hg.mozilla.org/mozilla-central/rev/7b4db2f1bf8f)). This has two b
Nit: that *is* not exposed to localization 
or
that's not exposed to localization

2021-08-27 01:38 UTC, Delphine commented on src/localization/dev_best_practices.md
> +
I'd add: "(...)from approved UX wireframes, *and* any copy review..."

2021-08-27 01:38 UTC, Delphine commented on src/localization/dev_best_practices.md
> +Another example is localizing percentages or units. Some locales use a space between the number and the `%` symbol, some don’t, some use a non-breaking space.
Would add at the end: "*and* some use a non-breaking space"

2021-08-27 01:38 UTC, Delphine commented on src/localization/dev_best_practices.md
> +For some formats, **plural forms are not supported**, for a limitation in either the format itself (DTD, JSON) or in our toolchain (XLIFF). In these cases, you should try to use plural neuter forms:
As for .xml as well

2021-08-27 04:17 UTC, flodolo commented on src/localization/dev_best_practices.md
> +Some CSS text/font properties may cause problems with text legibility when applied to certain scripts. For example, avoid using Italic for CJKT locales — Chinese (Simplified and Traditional), Japanes
Also, the acronym used is always CJK 🤦🏼

2021-08-27 04:21 UTC, flodolo commented on src/localization/dev_best_practices.md
> +
Ah no, that's a typo, it should be "and copy review"

2021-08-27 04:22 UTC, flodolo commented on src/localization/dev_best_practices.md
> +For some formats, **plural forms are not supported**, for a limitation in either the format itself (DTD, JSON) or in our toolchain (XLIFF). In these cases, you should try to use plural neuter forms:
Good point, I should also call XML out in the comment formats.

2021-08-27 04:26 UTC, flodolo commented
> Some of the sentences in the best practice guide seems to run long and colloquial.

Yes, too many cooks in the kitchen :-( This document was edited by way too many people, I fixed a lot of registry changes, but some are still around.

Thanks both, updated the doc and accepted all suggestions.

2021-08-31 21:39 UTC, Delphine approved these changes
Haven't noticed anything else missing at this point! Thanks flod

2021-09-01 05:23 UTC, flodolo commented
Thanks all for the help 👍🏼

2021-09-01 05:23 UTC, merged