Updated with details on new locales and quarantine PR
mozilla-l10n/documentation pull request #250
Opened 2021-12-15 04:06 UTC by Delphine

2021-12-15 07:12 UTC, flodolo requested changes
New lines are ineffective in markdown, i.e. the text is not displayed as you probably wanted
https://github.com/mozilla-l10n/documentation/blob/347b6884ea9b649969bffadb30104cb6f5ceff8d/src/products/android-l10n/adding_new_locales.md

This is not "probably", the next PR coming from the code repository will try to remove the new locales from l10n.toml until the PR is merged on the other side.

This is one of the cases where it's worth digging deeper to get information, and explain it clearly (with steps) for whoever needs to takeover.
* You merge the PR adding locales to TOML in the l10n repository. What happens next? What does the automation?
* There's a PR on the code side. What happens with the automation while this PR is pending?
* What do you need to do while you wait for the PR to be merged?

2021-12-16 01:32 UTC, Delphine commented
Thanks a lot for the feedback. This is not urgent at this point, so I will take the time to create a doc to address all the questions you mention.

2022-03-15 22:04 UTC, Delphine commented
This should be all udpated by now!

2022-03-16 05:45 UTC, flodolo approved these changes

2022-03-16 05:45 UTC, merged