Update firefox faq about uplifts
mozilla-l10n/documentation pull request #293
Opened 2024-12-20 21:23 UTC by bcolsson

Fixes #288

2024-12-20 21:45 UTC, peiying2 approved these changes
LGTM.

2025-01-02 07:24 UTC, flodolo requested changes

2025-01-02 07:24 UTC, flodolo commented on src/products/firefox_desktop/firefox_l10n_faqs.md
> +Uplifts need to be evaluated case by case, but in general they should be avoided in the context of a 4-weeks release cycle. Possible alternatives are uplifting ad-hoc patches without string changes,
This is a bit too vague.

First issue: the update doesn't "need" to be included. It should be included if we landed the strings and gave people time to translate them. If it's an urgent uplift, and the strings are still stuck in quarantine, no point in uplifting an updated `l10n-changesets.json`.

What does "include" mean? Include it in the patch for uplift, ask release managers to include the update?

What is an "update"? From where do you take the file to uplift, how does it look like?

2025-01-06 20:44 UTC, bcolsson commented on src/products/firefox_desktop/firefox_l10n_faqs.md
> +Uplifts need to be evaluated case by case, but in general they should be avoided in the context of a 4-weeks release cycle. Possible alternatives are uplifting ad-hoc patches without string changes,
Hopefully this [commit](https://github.com/mozilla-l10n/documentation/pull/293/commits/213d1d80edc076cc9a56d8d3b6729d444725bfc3) addresses your feedback.

>What does "include" mean? Include it in the patch for uplift, ask release managers to include the update?
I'm not sure if there's a better approach to what I added, but I think having the changes to `l10n-changesets.json` in the uplift patch would allow us an opportunity to review.

2025-01-07 06:48 UTC, flodolo commented on src/products/firefox_desktop/firefox_l10n_faqs.md
> +Uplifts need to be evaluated case by case, but in general they should be avoided in the context of a 4-weeks release cycle. Possible alternatives are uplifting ad-hoc patches without string changes,
That's an option if they need to create a separate patch for uplift, but typically the patch is uplifted as is. We should mention both options: ad-hoc patch including the updated file, or ask relman to land a follow-up change.

We also typically take the l10n-changesets file from mozilla-beta, even if it's not the latest, since it means it's gone through the build system at least once.

We should also link to https://mozilla-l10n.github.io/documentation/products/firefox_desktop/build_system.html#overview

2025-01-20 15:02 UTC, flodolo approved these changes

2025-01-20 15:02 UTC, flodolo commented on src/products/firefox_desktop/firefox_l10n_faqs.md
> +In the event an uplift request is made and approved, translations for uplifted strings should also be uplifted if they have landed and have had enough time for localization. For translations to appea
```suggestion
If the uplift request is approved, translations for uplifted strings should also be uplifted if there was enough time for localization. For translations to appear in the build, the `revision` value for all locales in [`l10n-changesets.json`](https://searchfox.org/mozilla-central/source/browser/locales/l10n-changesets.json) must have a commit hash containing the appropriate translations from [`firefox-l10n`](https://github.com/mozilla-l10n/firefox-l10n). Typically, the content of `l10n-changesets.json` from `mozilla-beta` is used since it has gone through the build system at least once (even if it isn’t the latest). There are two options to ensure these changes are uplifted: an ad-hoc patch including the updates to the `l10n-changesets.json` file ([example](https://hg.mozilla.org/releases/mozilla-esr128/rev/4298182958af)) or asking Release Management to land a follow-up change for the l10n changesets ([example](https://hg.mozilla.org/releases/mozilla-esr128/rev/213534997a7c)).
```

2025-01-21 18:21 UTC, merged