Reflect Pontoon changes in add new locale docs
mozilla-l10n/documentation pull request #60
Opened 2017-03-02 21:07 UTC by mathjazz

@flodolo r?

This is complicated. We should automate it. Maybe after we figure out what to do with bug 1343908.

2017-03-02 21:11 UTC, mathjazz commented
I'll also update field order and descriptions to match the docs:
https://github.com/mozilla/pontoon/compare/master...mathjazz:model-locale-order?expand=1

2017-03-03 05:25 UTC, flodolo requested changes
Wow, this definitely shouldn't be done manually :-\

Still, good to document how this add is generated, but we shouldn't be doing math here…

2017-03-03 05:25 UTC, flodolo commented on tools/pontoon/adding_new_locale.md
> +A script locale is written in. Find it in [CLDR Languages and Scripts](http://www.unicode.org/cldr/charts/latest/supplemental/languages_and_scripts.html).
The script used by the new locale.

2017-03-03 05:25 UTC, flodolo commented on tools/pontoon/adding_new_locale.md
> +---
Let's drop the hr

2017-03-03 05:25 UTC, flodolo commented on tools/pontoon/adding_new_locale.md
> +Number of native speakers. Find locale code in [CLDR territoryInfo.json](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/territoryInfo.json) and multiply its "_populationPercent" w
Use backticks instead of double quotes, i.e.
```
... and multiply its `_populationPercent` with the territory `_population`
```

2017-03-03 12:26 UTC, mathjazz commented
Updated.

I'll file a bug to simplify this after bug 1343908 gets resolved.

2017-03-03 12:31 UTC, flodolo approved these changes

2017-03-03 12:31 UTC, merged