Add test instruction to dynamic pages
mozilla-l10n/documentation pull request #65
Opened 2017-03-10 17:01 UTC by peiying2

- Need review and verify the steps
- Line #85, this page only exists on staging. Is there a production link?
- Line #89, can't seem to find a way to get to the Sync content. Are the messages for first time sync setup?
- Line #91, for this feature, I can’t get to this message as the feature is not offered in the current product: It’s easy to turn off Tracking Protection for the website you’re on by clicking “Disable protection for this site.”

2017-03-10 18:15 UTC, flodolo requested changes

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +## Testing Dynamic Pages
No title case

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +This section focuses on instructions for testing pages with dynamically generated content. Each page or topic is different in terms of steps or flow. These instructions could change overtime to refle
overtime -> over time

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +.. * Desktop: Windows, macOS, Linux
Use a tab, not .. Checkout out of the page looks like
https://github.com/mozilla-l10n/documentation/blob/933bda12d046a80b2fc255bd0a02ffce7b2d381e/products/mozilla_org/test_mozilla_org.md

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* Start a new browser by clicking on the Firefox icon, select New Private Window on the menu list
You can simplify here: "Open Firefox and start a New private window"

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +You can check out the manifestos without going to the slide mode. However, only in the slide mode, all the localized content can be reviewed.
the manifestos -> manifesto's principles?

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* Click on the first manifesto
manifesto -> principle

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +There are different ways to access the signup dialog box above the footer area.  This is from the Contribute page.
No double spaces after a period

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* Click on any of the six icons or the links below each of them, you will be prompt to the Sign Up section
prompt -> prompted

2017-03-10 18:15 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* Leave the name field empty, click on the **Sign Up Now** button. A text bubble will appear
Note that this is the sign-up for the newsletter, not for the contribute page. That's available even at the bottom of the home page.

The error bubbles come from Firefox, e.g. try signing up at the bottom of the Italian page, the warning will be in English https://www.mozilla.org/it/

Personally I would drop this section

2017-03-10 18:20 UTC, flodolo commented
> Line #85, this page only exists on staging. Is there a production link?

sendto is enabled only for a few locales, on www-dev is enabled for all, that's why the link to dev server

> Line #89, can't seem to find a way to get to the Sync content. Are the messages for first time sync setup?

Can you explain exactly what content (strings) you're trying to reach? I can check the code to see if they're still used.

> Line #91, for this feature, I can’t get to this message as the feature is not offered in the current product: It’s easy to turn off Tracking Protection for the website you’re on by clicking “Disable protection for this site.”

As far as I can see, you can only get to "Disable protection for this session".

2017-03-10 18:23 UTC, flodolo commented
> As far as I can see, you can only get to "Disable protection for this session".

Found. You can only see "for this site" enabling TP in normal mode
https://bugzilla.mozilla.org/show_bug.cgi?id=1246461

2017-03-10 19:02 UTC, peiying2 commented on products/mozilla_org/test_mozilla_org.md
> +## Testing Dynamic Pages
The whole doc is in this format.  Updating all titles except for the title of the document.

2017-03-10 19:02 UTC, peiying2 commented on products/mozilla_org/test_mozilla_org.md
> +This section focuses on instructions for testing pages with dynamically generated content. Each page or topic is different in terms of steps or flow. These instructions could change overtime to refle
done.

2017-03-10 19:03 UTC, peiying2 commented on products/mozilla_org/test_mozilla_org.md
> +.. * Desktop: Windows, macOS, Linux
fixed.

2017-03-10 19:21 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* If it doesn't or it stops, click the next or previous arrows to go to the next slide
Looks like there's a rogue straight quote instead of an apostrophe

2017-03-10 19:21 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +There are different ways to access the signup dialog box above the footer area. This is for signing up newsletters.
I think it should be "signing up to newsletters"

2017-03-10 19:25 UTC, flodolo commented
To answer your question, these are locales enabled on prod for sendto
https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1122-L1125

2017-03-10 19:42 UTC, flodolo requested changes

2017-03-10 19:42 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* For alternative message, change URL to [Scene2](https://www.mozilla.org/en-US/firefox/new/?scene=2)
Remove en-US from the link

2017-03-10 19:42 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* You are taken to [step one](https://www.mozilla.org/en-US/firefox/51.0.1/tracking-protection/start/?step=1)
Remove en-US from all these link

2017-03-10 20:02 UTC, flodolo commented on products/mozilla_org/test_mozilla_org.md
> +* Language list: Is your language listed as one of the options? Check https://www-dev.allizom.org/ to confirm
Commenting again here, since doing it on a commit is confusing: this one actually needs to point to /en-US

2017-03-13 20:50 UTC, peiying2 commented
For the sync.lang file, half of its content is for the current static page, the other half is either obsolete or a part of a dynamic page flow.  

@TheoChevalier, @flodolo, we can remove the sync and signup sections if the rest of the newly added content is ok.  so we can release it for the agencies that need it.  We can figure out what to add for sync and if we need to keep signup page.

2017-03-13 20:54 UTC, flodolo commented
At this point I would drop both those parts, and eventually update the doc later if it's needed.

2017-03-13 21:06 UTC, flodolo approved these changes

2017-03-13 21:06 UTC, flodolo commented
Good to merge for me (you should be able to do it directly now).

2017-03-13 21:07 UTC, merged